### ISSUE TITLE
reply_all.py和box.py

### ISSUE THREAD

**Issue by xidaner** [Voevodsky/tieba-manage#1]
这俩有区别？

**Comment by Voevodsky** [comment]
一个是获取某个帖子内的所有楼层，一个是获取某个用户的所有回复贴

**Comment by xidaner** [comment]
你确定存在代码有获取某个帖子内的所有楼层 ???? 我看代码都是通过uid获取恢复的内容啊 主题帖和回复贴 不像你说的 通过多线程扫描所有的回复内容 通过get_comment来实现？

**Comment by Voevodsky** [comment]
reply_all.py就是，get_post获得楼层，get_comment获得楼中楼啊

**Comment by Voevodsky** [comment]
我去，原来是文件传错了,已更新....

**Comment by xidaner** [comment]
![Uploading Snipaste_2024-04-24_11-44-14.jpg…]()

**Comment by xidaner** [comment]
没事了 👌👌
